" TODO: figure out how to make this NERDTreeFind not run when we got to a
" help file. that shit has been annoying me for years
au VimEnter,BufWinEnter * NERDTreeFind

"colorscheme solarized
colorscheme railscasts

set background=dark

"set background to almost but not quite black
hi Normal guibg=Grey2

set guitablabel=%f

nmap <C-Tab> :tabn<CR>
nmap <C-S-Tab> :tabp<CR>

se guioptions=agim
se guioptions=-e
