set nocompatible                " choose no compatibility with legacy vi
""Updated based on
""http://vimcasts.org/episodes/synchronizing-plugins-with-git-submodules-and-pathogen/

runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()

syntax enable
filetype plugin indent on
colorscheme desert

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode
set smartindent
set encoding=utf-8
set showcmd                     " display incomplete commands

"" Searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

let g:ruby_path = "/Users/williamh/.rvm/rubies/jruby-1.6.7/bin/ruby"

au BufNewFile,BufRead *.html.erb set syntax=eruby

"This unsets the "last search pattern" register by hitting return
nnoremap <CR> :noh<CR><CR>
