set nocompatible                " choose no compatibility with legacy vi
""Updated based on
""http://vimcasts.org/episodes/synchronizing-plugins-with-git-submodules-and-pathogen/

runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
call pathogen#helptags() " have pathogen update all help files  on load

syntax enable
filetype plugin indent on
colorscheme desert

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode
set smartindent
set encoding=utf-8
set showcmd                     " display incomplete commands

"" Searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

"ruby syntax
au BufNewFile,BufRead *.html.erb set syntax=eruby

"help vim understand css files that get processed with other things as well
autocmd BufNewFile,BufRead *.css*          set ft=css

"sass syntax
au BufRead,BufNewFile *.scss* set filetype=scss

"""""" autocompletions and options {{{
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType scss set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#Complete

set wildmenu


"" make the autocompleters give you the longest list to chose from all the time

set completeopt+=longest
set wildmode=list:longest
""""""""""""" }}}

"auto add semicolon's in css
autocmd FileType css inoremap <buffer> : :;<Esc>i

"This unsets the "last search pattern" register by hitting return
nnoremap <CR> :noh<CR><CR>

let g:ragtag_global_maps = 1

" Get running OS
function! GetRunningOS()
  if has("win")
    return "win"
  endif
  if has("unix")
    if system('uname')=~'Darwin'
      return "mac"
    else
      return "linux"
    endif
  endif
endfunction

let os=GetRunningOS()

if os=="linux"
  let g:netrw_home=$HOME . "/.vimfiles" "get rid of pesky .netrwhist file in our vim directory
  "make linux vim work with ctrl+v and ctrl+c
  vmap <C-c> "+yi
  vmap <C-x> "+c
  vmap <C-v> c<ESC>"+p
  imap <C-v> <C-r><C-o>+
  
  "get rid of graphical icons for header menu and use much better text one
  se guioptions=agim
endif


" ctrl p stuff
let g:ctrlp_extensions = ['tag']
let g:ack_qhandler='CtrlPQuickfix'
let g:ctrlp_max_files = 200000
" make file search MUUUUUUUCH faster by only looking at tracked files in git
" dirs
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux"

" fzf
set rtp+=~/.fzf

"trailin whitespace
" http://stackoverflow.com/questions/356126/how-can-you-automatically-remove-trailing-whitespace-in-vim
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()


"ag
let g:ackprg = 'ag --vimgrep'
cnoreabbrev Ack Ack!
